### ISSUE TITLE
Compile Issues

### ISSUE THREAD

**Issue by davidpeterunderhill** [SergeyMi37/cache-iris-app-tools#2]
The zen based classes will not compile with the russian character set used for labels and text values on a Western ISO NLS IRIS installation.

**Comment by SergeyMi37** [comment]
Hi, David
To translate the application menu items you need to import into the global system
^%AppCacheMsg 
Which can be found in the installation directory of the project 
apptools\src\glb\appcachemsg.xml

**Comment by davidpeterunderhill** [comment]
Thank you for the update and hard work.

Regards David
